# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f4838a3003e39b05db02d6451f507b7ff02fc0d0dfa55f16e18c73f05f0545a6ec407db16b34b4c3b3aea72040f6cb335f673d89ee7e60efb6ddfd7db9a5fb5

test:
  secret_key_base: 49733620a148f811ec9808651975b7a29648fb801d89cd7649a418608565217f6e8924a4cd5c78461299cdf3714222827f00cc4bde8649b80ce13796c79bed9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
